---
subtitle: "for Real-Time Radiance Field Rendering"
---

# Gasussian Splatting 3D 


## Abstract [(web)](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/)

Radiance Field methods have recently revolutionized novel-view synthesis of scenes captured with multiple photos or videos. However, achieving high visual quality still requires neural networks that are costly to train and render, while recent faster methods inevitably trade off speed for quality. For unbounded and complete scenes (rather than isolated objects) and 1080p resolution rendering, no current method can achieve real-time display rates.


We introduce three key elements that allow us to achieve state-of-the-art visual quality while maintaining competitive training times and importantly allow high-quality real-time (≥ 100 fps) novel-view synthesis at 1080p resolution. 


1. First, starting from sparse points produced during camera calibration, we represent the scene with 3D Gaussians that preserve desirable properties of continuous volumetric radiance fields for scene optimization while avoiding unnecessary computation in empty space; 

2. Second, we perform interleaved optimization/density control of the 3D Gaussians, notably optimizing anisotropic covariance to achieve an accurate representation of the scene;

3. Third, we develop a fast visibility-aware rendering algorithm that supports anisotropic splatting and both accelerates training and allows realtime rendering. We demonstrate state-of-the-art visual quality and real-time rendering on several established datasets.


## Explanation

[3D Gaussian Splatting. David Cochard](https://medium.com/axinc-ai/3d-gaussian-splatting-real-time-rendering-of-photorealistic-scenes-f7f1a47f060)

## Experimentation

{{< var 3d_gauss_sp.github >}}      




## Postprocess

Renderizado Volumétrico -> Malla

### Unity


[](https://www.youtube.com/watch?v=KaAxGr_xck4)

[](https://youtu.be/5_GaPYBHqOo)

